# Generated by Django 5.0.6 on 2024-05-26 13:06

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('spotify_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('artists', models.CharField(db_column='artists', max_length=500)),
                ('image', models.ImageField(upload_to='songs')),
                ('youtube_video_id', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Date-Time')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('spotify_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='playlists')),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Date-Time')),
                ('tracks', models.ManyToManyField(to='songdownloader.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('mode', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('spotify_id', models.CharField(max_length=120)),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
