# Generated by Django 5.0.6 on 2024-05-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdownloader', '0003_userhistory_userlogrecent_delete_userlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogrecent',
            old_name='spotify_id',
            new_name='service_id',
        ),
    ]
