# Generated by Django 5.0.6 on 2024-05-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdownloader', '0004_rename_spotify_id_userlogrecent_service_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='SpotifyPlaylist',
        ),
        migrations.RenameModel(
            old_name='Song',
            new_name='SpotifySong',
        ),
    ]
