# Generated by Django 5.0.6 on 2024-06-01 15:32

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdownloader', '0005_rename_playlist_spotifyplaylist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSong',
            fields=[
                ('youtube_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('artists', models.CharField(db_column='artists', max_length=500)),
                ('image', models.ImageField(upload_to='songs')),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Date-Time')),
            ],
            options={
                'verbose_name': 'YouTube Song',
            },
        ),
        migrations.AlterModelOptions(
            name='spotifyplaylist',
            options={'verbose_name': 'Spotify Playlist'},
        ),
        migrations.AlterModelOptions(
            name='spotifysong',
            options={'verbose_name': 'Spotify Song'},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name': 'User History', 'verbose_name_plural': 'User History'},
        ),
        migrations.AlterModelOptions(
            name='userlogrecent',
            options={'verbose_name': 'User Logs (Recent)', 'verbose_name_plural': 'User Logs (Recent)'},
        ),
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('youtube_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='playlists')),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Creation Date-Time')),
                ('tracks', models.ManyToManyField(to='songdownloader.youtubesong')),
            ],
            options={
                'verbose_name': 'YouTube Playlist',
            },
        ),
    ]
