# Generated by Django 5.0.6 on 2024-06-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdownloader', '0006_youtubesong_alter_spotifyplaylist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyplaylist',
            old_name='spotify_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='spotifysong',
            old_name='spotify_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='youtubeplaylist',
            old_name='youtube_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='youtubesong',
            old_name='youtube_id',
            new_name='id',
        ),
    ]
