{
 "title": "Celery Tasks Dashboard",
 "description": "Simple dashboard for monitoring Celery tasks and workers. Suitable for Python developers who use Celery along with Flask, Django or FastAPI",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(celery_worker_up,instance)"
    }
   },
   {
    "name": "tasks",
    "label": "tasks",
    "query": {
     "query": "label_values(celery_task_received_total,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Celery Worker Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker Status",
   "type": "stat",
   "description": "Indicates if a worker has recently sent a heartbeat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_worker_up{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active Worker Count",
   "type": "stat",
   "description": "The number of active workers in broker queue",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_active_worker_count{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Proccess Count",
   "type": "stat",
   "description": "The number of active process in broker queue. Each worker may have more than one process",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_active_process_count{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "stat",
   "description": "The number of message in broker queue",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_queue_length{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Tasks Active",
   "type": "timeseries",
   "description": "The number of tasks the worker is currently processing",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "celery_worker_tasks_active{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Task Success Rate",
   "type": "gauge",
   "description": "Histogram of runtime measurements for each task",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_task_succeeded_total{})/(sum(celery_task_failed_total{}) + sum(celery_task_succeeded_total{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Celery Tasks Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Sent Tasks Total",
   "type": "timeseries",
   "description": "Sent when a task message is published",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(celery_task_sent_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Received Tasks Total",
   "type": "timeseries",
   "description": "Sent when the worker receives a task",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "increase(celery_task_received_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Started Tasks Total",
   "type": "timeseries",
   "description": "Sent just before the worker executes the task",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(celery_task_started_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Succeeded Tasks Total",
   "type": "timeseries",
   "description": "Sent if the task executed successfully",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "increase(celery_task_succeeded_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Failed Tasks Total",
   "type": "timeseries",
   "description": "Sent if the execution of the task failed",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(celery_task_failed_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}_{{ exception }}"
    }
   ]
  },
  {
   "title": "Retried Tasks Total",
   "type": "timeseries",
   "description": "Sent if the task failed, but will be retried in the future",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "increase(celery_task_retried_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Revoked Tasks Total",
   "type": "timeseries",
   "description": "Sent if the task has been revoked",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(celery_task_revoked_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Rejected Tasks Total",
   "type": "timeseries",
   "description": "The task was rejected by the worker, possibly to be re-queued or moved to a dead letter queue",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "increase(celery_task_rejected_total{instance=~\"$instance\", name=~\"$tasks\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}