# Generated by Django 5.0.6 on 2024-06-18 11:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_passwords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=5)),
                ('token', models.CharField(max_length=255)),
                ('token_updated', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Profile',
                'verbose_name_plural': 'Password Profiles',
                'ordering': ['-updated'],
                'get_latest_by': 'updated',
                'unique_together': {('token', 'previous_passwords')},
            },
        ),
    ]
