# Generated by Django 5.0.6 on 2024-06-24 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_passwords', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Profile',
                'verbose_name_plural': 'Password Profiles',
                'ordering': ['-updated'],
                'get_latest_by': 'updated',
            },
        ),
    ]
