# Generated by Django 5.0.6 on 2024-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_passwordsprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordsprofile',
            name='previous_passwords',
        ),
        migrations.AddField(
            model_name='passwordsprofile',
            name='old_passwords',
            field=models.JSONField(default=list),
        ),
    ]
