global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Gunicorn'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'Celery'
    static_configs:
      - targets: ['celery-exporter:9808', 'flower:5555']

  - job_name: 'Postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'Redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'Prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: Host-Machine
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: Docker-Monitor
    static_configs:
      - targets: ['cadvisor:8080']

